window.SARAH_PRODUCTS = [
  {id:'netflix-1m',cat:'streaming',name:'Netflix',option:'1 Month',price:3},
  {id:'netflix-3m',cat:'streaming',name:'Netflix',option:'3 Months',price:8},
  {id:'netflix-life',cat:'streaming',name:'Netflix',option:'Lifetime',price:22},
  {id:'crunchyroll-1m',cat:'streaming',name:'Crunchyroll',option:'1 Month',price:3},
  {id:'crunchyroll-3m',cat:'streaming',name:'Crunchyroll',option:'3 Months',price:7},
  {id:'crunchyroll-life',cat:'streaming',name:'Crunchyroll',option:'Lifetime',price:18},
  {id:'hbomax-1m',cat:'streaming',name:'HBO Max',option:'1 Month',price:4},
  {id:'hbomax-3m',cat:'streaming',name:'HBO Max',option:'3 Months',price:10},
  {id:'hbomax-life',cat:'streaming',name:'HBO Max',option:'Lifetime',price:25},
  {id:'spotify-12m',cat:'streaming',name:'Spotify',option:'12 Months',price:5},
  {id:'spotify-life',cat:'streaming',name:'Spotify',option:'Lifetime',price:10},
  {id:'prime-1m',cat:'streaming',name:'Prime Video',option:'1 Month',price:3},
  {id:'prime-3m',cat:'streaming',name:'Prime Video',option:'3 Months',price:8},
  {id:'prime-life',cat:'streaming',name:'Prime Video',option:'Lifetime',price:20},
  {id:'paramount-1m',cat:'streaming',name:'Paramount+',option:'1 Month',price:3},
  {id:'paramount-3m',cat:'streaming',name:'Paramount+',option:'3 Months',price:7},
  {id:'paramount-life',cat:'streaming',name:'Paramount+',option:'Lifetime',price:18},
  {id:'chatgpt-1m',cat:'ai',name:'ChatGPT',option:'1 Month',price:6},
  {id:'chatgpt-3m',cat:'ai',name:'ChatGPT',option:'3 Months',price:15},
  {id:'claude-1m',cat:'ai',name:'Claude',option:'1 Month',price:5},
  {id:'claude-3m',cat:'ai',name:'Claude',option:'3 Months',price:13},
  {id:'gemini-1m',cat:'ai',name:'Gemini',option:'1 Month',price:4},
  {id:'gemini-3m',cat:'ai',name:'Gemini',option:'3 Months',price:10},
  {id:'boost-small',cat:'discord',name:'Server Boosts',option:'Small Pack',price:4},
  {id:'boost-medium',cat:'discord',name:'Server Boosts',option:'Medium Pack',price:8},
  {id:'boost-large',cat:'discord',name:'Server Boosts',option:'Large Pack',price:15},
  {id:'members-starter',cat:'discord',name:'Real Members',option:'Starter',price:5},
  {id:'members-medium',cat:'discord',name:'Real Members',option:'Medium',price:10},
  {id:'members-large',cat:'discord',name:'Real Members',option:'Large',price:20},
  {id:'tiktok-basic',cat:'social',name:'TikTok',option:'Basic Package',price:5},
  {id:'tiktok-medium',cat:'social',name:'TikTok',option:'Medium Package',price:10},
  {id:'tiktok-large',cat:'social',name:'TikTok',option:'Large Package',price:20},
  {id:'instagram-basic',cat:'social',name:'Instagram',option:'Basic Package',price:5},
  {id:'instagram-medium',cat:'social',name:'Instagram',option:'Medium Package',price:10},
  {id:'instagram-large',cat:'social',name:'Instagram',option:'Large Package',price:20},
  {id:'youtube-basic',cat:'social',name:'YouTube',option:'Basic Package',price:5},
  {id:'youtube-medium',cat:'social',name:'YouTube',option:'Medium Package',price:12},
  {id:'youtube-large',cat:'social',name:'YouTube',option:'Large Package',price:25},
  {id:'fortnite-starter',cat:'gaming',name:'Fortnite',option:'Starter',price:8},
  {id:'fortnite-better',cat:'gaming',name:'Fortnite',option:'Better Account',price:15},
  {id:'fortnite-premium',cat:'gaming',name:'Fortnite',option:'Premium Account',price:25},
  {id:'valorant-starter',cat:'gaming',name:'Valorant',option:'Starter',price:7},
  {id:'valorant-better',cat:'gaming',name:'Valorant',option:'Better Account',price:15},
  {id:'valorant-premium',cat:'gaming',name:'Valorant',option:'Premium Account',price:25}
];
